### PR TITLE
OrderBillingAddress column removed from order table

### PR DESCRIPTION
**Pull request by RahulJha-mastek**
Story [AB#9714](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/9714)
Task [AB#7941](https://buyingcatalog.visualstudio.com/c5f97979-5b03-4d10-ba8d-871d0526b408/_workitems/edit/7941)

OrderBillingAddress column removed from order table

### CODE REVIEW

**Review by bjss-chris — CHANGES_REQUESTED** [review]
Your changes look good. However, before I approve can you squash your commits and reword your commit message?

Your commit message should be written in the imperative. Therefore, I'd recommend rewording your commit message to something like: 'Remove OrderBillingAddressId column from Order table'

**Comment by RahulJha-mastek** [comment]
> Your changes look good. However, before I approve can you squash your commits and reword your commit message?
> 
> Your commit message should be written in the imperative. Therefore, I'd recommend rewording your commit message to something like: 'Remove OrderBillingAddressId column from Order table'

I have updated Commit message.

**Comment by RahulJha-mastek** [comment]
> Your changes look good. However, before I approve can you squash your commits and reword your commit message?
> 
> Your commit message should be written in the imperative. Therefore, I'd recommend rewording your commit message to something like: 'Remove OrderBillingAddressId column from Order table'

**Comment by RahulJha-mastek** [comment]
reopening the pull request, closed accidently

**Review by bjss-chris — APPROVED** [review]

**Comment by bjss-chris** [comment]
Approved. Select squash and merge to squash your commits down to one.

**Pull request merged**
